### ISSUE TITLE
Task-1: Kali Linux

### ISSUE THREAD

**Issue by RickyTheDude** [opencodeiiita/FreshHat-Learning-Repository#2]
### Task 1: Install Kali Linux in a Virtual Machine  

Use a hypervisor of your choice:  
- VMware  
- VirtualBox  
- Hyper-V  
- QEMU  
- Any other preferred option  

💡 **Follow this guide for detailed instructions:**  
[Kali Linux VirtualBox Installation Guide](https://www.kali.org/docs/virtualization/install-virtualbox-guest-vm/)  

Happy virtualizing! 😊

**Comment by PriyamJChakrabarty** [comment]
Claim
