### ISSUE TITLE
Task-2: Python program

### ISSUE THREAD

**Issue by RickyTheDude** [opencodeiiita/FreshHat-Learning-Repository#3]
### Task 2: Write a Basic Python Program  

📌 **Objective:**  
Write a Python program that prints "Hello, World!" and run it on the terminal.  

🎯 **Submission Format:**  
- Submit the code (file content).  
- Attach a screenshot of the terminal showing the program output.

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by ASHTAD123** [comment]
Task-2: Python program #3

Executed Python Program on Kali Linux Terminal
Added  Screenshot link & code 
Link : https://drive.google.com/file/d/1dDJOefZeSHShDHm5KG25pGr4Ekani0-a/view?usp=sharing

![Task_2_Python_Program](https://github.com/user-attachments/assets/6749a38c-3bc5-4b54-9655-33ae49e90520)

**Comment by Butterfly222-kartiki** [comment]
basic python program

**Comment by vanditajain-29** [comment]
> ### Task 2: Write a Basic Python Program
> 📌 **Objective:** Write a Python program that prints "Hello, World!" and run it on the terminal.
> 
> 🎯 **Submission Format:**
> 
> * Submit the code (file content).
> * Attach a screenshot of the terminal showing the program output.

Issue 2

print("Hello World")
#https://drive.google.com/file/d/1mUw3GugLtP7B9SR7knETjFIJ7JLZn7kU/view
